[package]
name = "netaudio-server"
version = "1.0.0"
authors = ["Raffael Zica <raffael@pixeltastic.de>"]
edition = "2018"

[dependencies]
byteorder = "1.3.2"
cpal = "0.8"
getopts = "0.2"

[dependencies.rodio]
version = "0.9.0"
