[package]
name = "netaudio-server"
version = "1.1.0"
authors = ["Raffael Zica <raffael@pixeltastic.de>"]
edition = "2018"

[dependencies]
byteorder = "1.3.2"
getopts = "0.2"
cpal = "0.10"
rodio = {git = "https://github.com/RustAudio/rodio"}