[package]
name = "netaudio-source"
version = "1.0.0"
authors = ["Raffael Zica <raffael@pixeltastic.de>"]
edition = "2018"

[dependencies]
byteorder = "1.3.2"
cpal = {git = "https://github.com/lucy/cpal"}
getopts = "0.2"